# The version of the Docker compose file format to use.
version: '3.7'

services:

  # Serves static content and forwards requests to servers.
  nginx:
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    tty: true
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./:/quasar
    depends_on:
      - nexus_courier

  # RabbitMQ broker.
  rabbit_manager:
    build:
      context: .
      dockerfile: ./applications/rabbitmq_manager/Dockerfile
    tty: true
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit_manager
    # TODO: switch to COPY cmd?
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"

  rabbit2:
    build:
      context: .
      dockerfile: ./applications/nexus_server/Dockerfile
    tty: true
    hostname: rabbit2
    depends_on:
      - rabbit_manager
    environment:
      - PYTHONPATH=:/quasar
      - RABBITMQ_ERLANG_COOKIE="secret string"
      - RABBITMQ_NODENAME=rabbit2
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./:/quasar

  nexus_courier:
    build:
      context: .
      dockerfile: ./applications/nexus_courier/Dockerfile
    environment:
      - PYTHONPATH=:/quasar
      - RABBITMQ_ERLANG_COOKIE="secret string"
      - RABBITMQ_NODENAME=nexus_courier
    tty: true
    hostname: nexus_courier
    depends_on:
      - rabbit_manager
    #depends_on:
    #  - rabbit_host
    #networks:
    #  - rabbitmq_network
    #ports:
    #  - "3001:3001"
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./:/quasar
    #depends_on:
    #  - nginx

networks:
  default:
    name: rabbitmq_cluster
