# The version of the Docker compose file format to use.
version: '3'

services:

  quality_assurance:
    build: ./quasar_micro_applications/quality_assurance
    container_name: quasar_service_quality_assurance
    environment:
      - MICRO_SERVICE_NAME=quasar_service_quality_assurance
    #ports:
    #  - "1338:1338"
    #  - "1339:1339"

  nexus_local:
    build: ./quasar_micro_applications/quasar_nexus/nexus_local
    container_name: quasar_service_nexus_local
    environment:
      - MICRO_SERVICE_NAME=quasar_service_nexus_local
    ports:
      - "1337:1337"

  nexus_server:
    build: ./quasar_micro_applications/quasar_nexus/nexus_server
    container_name: quasar_service_nexus_server
    environment:
      - MICRO_SERVICE_NAME=quasar_service_nexus_server
    #ports:
    #  - "1340:1340"

  db:
    build: ./quasar_micro_applications/quasar_db
    container_name: quasar_service_database
    environment:
      - MICRO_SERVICE_NAME=quasar_service_database
    #ports:
    #  - "1338:1338"
    #  - "1339:1339"
