# The version of the Docker compose file format to use.
version: '3'

services:

  # Control point for build process + management for the QA, STAGE, PROD environments.
  #nexus_server:


  # Local development 3D web interface.
  nexus_local:
    build: ./applications/nexus/local
    environment:
      - DJANGO_SECRET_KEY=gvb9f175igbse7329ei3pl72p73fehn8g2opwtetc2ihh4325a
      - SQLITE_DB_PATH=/quasar/generated_output/local/nexus_local_db.sqlite
      - PYTHONPATH=:/quasar
      - DJANGO_SETTINGS_MODULE=nexus_local.settings
    ports:
      - "1337:1337"
    volumes:
      - ./:/quasar
    depends_on:
      - redis

  # Needed for Django Channels (web-sockets).
  redis:
    build: ./applications/redis/
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data:

######

  #nexus_server:
  #  build: ./applications/quasar_nexus/nexus_server
  #  container_name: quasar_service_nexus_server
  #  environment:
  #    - MICRO_SERVICE_NAME=quasar_service_nexus_server


  #  restart: always

  #nginx:
  #  restart: always
  #  image: nginx

  #quality_assurance:
  #  build: ./applications/quality_assurance
  #  container_name: quasar_service_quality_assurance
  #  environment:
  #    - MICRO_SERVICE_NAME=quasar_service_quality_assurance

  #db:
  #  build: ./applications/quasar_db
  #  container_name: quasar_service_database
  #  environment:
  #    - MICRO_SERVICE_NAME=quasar_service_database


