# The version of the Docker compose file format to use.
version: '3.7'

services:

  # Control point for build process + management for the QA, STAGE, PROD environments.
  #nexus_server:

  # Serves static content.
  nginx:
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    tty: true
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./:/quasar
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: ./applications/nexus_server/Dockerfile
    tty: true
    #ports:
    #  - "3001:3001"
    volumes:
      - ./:/quasar
    #depends_on:
    #  - nginx

  # Local development 3D web interface.
#  nexus_local:
#    build: ./applications/nexus/local
#    environment:
#      - DJANGO_SECRET_KEY=gvb9f175igbse7329ei3pl72p73fehn8g2opwtetc2ihh4325a
#      - SQLITE_DB_PATH=/quasar/generated_output/local/nexus_local_db.sqlite
#      - PYTHONPATH=:/quasar
#      - DJANGO_SETTINGS_MODULE=nexus_local.settings
#    tty: true
#    ports:
#      - "1337:1337"
#    volumes:
#      - ./:/quasar
#    depends_on:
#      - redis
#      - nginx

  # Needed for Django Channels (web-sockets).
#  redis:
#    build: ./applications/redis/
#    command: redis-server
#    tty: true
#    ports:
#      - "6379:6379"
#    volumes:
#      - 'redis_data:/data'

volumes:
  redis_data:



#websocket_server