# The version of the Docker compose file format to use.
version: '3.7'

services:

  # Builds projects.
  code_manager:
    build:
      context: .
      dockerfile: ./applications/code_manager/Dockerfile
    environment:
      - PYTHONPATH=:/quasar
      - CODE_BUILDER_DB_PATH=/quasar/generated_output/local/code_manager/db.sqlite
      - DB_DEBUG=False
      - LD_LIBRARY_PATH=/usr/lib/libamqpcpp.so.3.1
    tty: true
    #tty: false
    volumes:
      - ./:/quasar
      - persistent_volume:/persistent_volume_test

networks:
  default:
    external:
      name: host_connection

volumes:
  persistent_volume:
    external: true
