# The version of the Docker compose file format to use.
version: '3.7'

services:

  # Control point for build process + management for the QA, STAGE, PROD environments.
  #nexus_server:

  # Serves static content. TODO: Route to django.
  nginx:
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/quasar


